version: "3.8"

services:
  bambu-dashboard:
    build: .
    container_name: bambu_dashboard
    restart: unless-stopped
    network_mode: "host"
    environment:
      DASH_USER: "admin"
      DASH_PASS: "change-me"
    volumes:
      - ./config.json:/app/config.json:ro
